### ISSUE TITLE
How to implement this in Ionic 3 / Angular 2 project

### ISSUE THREAD

**Issue by Chethannp** [ahaw/ngx_photoswipe#1]
I am new to ionic and angular 2 coding and I am not able to understand on how to implement this project in my ionic 3 / angular 2 project. Can you please give a clear documentation please.

**Comment by ahaw** [comment]
I've never used ionic so I cannot help you but if you need example of usage in pure angular2+ then look into https://github.com/ahaw/ngx_photoswipe/tree/master/src/demo

**Comment by Chethannp** [comment]
I did try this but I am getting this error.

compiler.js:486 Uncaught Error: Template parse errors:
'ngx-lightbox' is not a known element:
1. If 'ngx-lightbox' is an Angular component, then verify that it is part of this module.
2. If 'ngx-lightbox' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

I even tried copying the gallery files to my project, this is the same error even there.

Also, Since I am looping through a div I was looking for html attribute feature.

**Comment by ahaw** [comment]
Which version of angular are you using? 6.x? 
I had this problem when library was using 5.x and application 6.x. 

I updated ngx-photoswipe npm package to 0.0.23 based on angular 6.x. Later I'll update repository as well
